# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'MovieListDemo' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for MovieListDemo
  pod 'SVProgressHUD'
  pod 'Alamofire', '5.4.1'


  target 'MovieListDemoTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'MovieListDemoUITests' do
    # Pods for testing
  end

end
